name: Generate Resume PDF

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      
      - run: chrome --version

      - name: Install dependencies
        run: yarn install

      - name: Generate PDF
        run: node generate-resume-pdf.js

      - name: Release 🚀
        uses: ncipollo/release-action@v1
        with:
          artifacts: resume.pdf